apiVersion: app/v1
kind: Deployment
metadata:
  labels:
    app: research
  name: research
spec:
  replicas: 2
  selector:
    matchLabels:
      app: research
  template:
    metadata:
      labels:
        app: research
    spec:
      containers:
      - image: research:v2
        resources:
        limits:
          memory: "520Mi"
          cpu: "0.3"
        requests:
          cpu: "0"
          memory: "0" 
        env:
         - name: VOLUME
           value: "/var/log/heartbeat"
        name: research
        volumeMounts:
        - mountPath: "/var/log/heartbeat"
          name: research-vol
      volumes:
      - name: research-vol
        persistentVolumeClaim: 
          claimName: research-pvc
      restartPolicy: Always