apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.3"
            memory: "520Mi"
          requests:
            cpu: "0"
            memory: "0"
        env:
         - name: USER_NAME   
           valueFrom:
              secretKeyRef:
                name: sql-secret
                key: sql-user          
         - name: USER_PWD
           valueFrom:
             secretKeyRef:
               name: sql-secret
               key: sql-password
         - name: DB_URL
           valueFrom:  
             configMapKeyRef:
               name: sql-config
               key: sql-url
               
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30200